[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["version", "description"]

[project.optional-dependencies]
doc = [
    "sphinx~=4.2.0",
    "myst_parser",
    "nbsphinx",
    "sphinx-theme",
    "jieba",
    "sphinxcontrib-plantuml",
    "sphinxcontrib-mermaid",
    "sphinx-autobuild"
]
